config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.nil?
      can :read, Post
    else
      can :manage, Post, user: user
      can :read, Post
      can :manage, Comment, user: user
      can :read, Comment
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	load_and_authorize_resource :post
	load_and_authorize_resource :comment, through: :post
	before_action :authenticate_user!

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.build(comment_params.merge(user: current_user))
		if @comment.save
			redirect_to @post, alert: "Successfully added a comment"
		else
			redirect_to @post, alert: "Failed to add comment"
		end
	end

	def destroy
		byebug
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])

		if @comment.user == current_user
			@comment.destroy
			redirect_to @post, notice: "Comment Successfully deleted"
		else
			redirect_to @post, notice: "You are not authorised to delete this comment"
		end
	end

	private

	def comment_params
		params.require(:comment).permit(:body)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	load_and_authorize_resource
	before_action :authenticate_user!, except: [:index, :show]
	before_action :set_post, only: [:show, :edit, :update, :destroy]
	before_action :authorize_user!, only: [:edit, :update, :destroy]


	def index
		@posts = Post.all
	end

	def show
	end

	def new
		@post = Post.new
	end

	def create
		@post = current_user.posts.build(post_params)
		if @post.save
			redirect_to @post, notice: "Post was successfully created"
		else
			render :new
		end
	end

	def edit
	end

	def update
		if @post.update(post_params)
			redirect_to posts_url, notice: "Post was successfully updated"
		else
			render :edit
		end
	end

	def destroy
		@post.destroy
		redirect_to posts_url, notice: "Post was destroyed"
	end


	private

	def set_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:title, :body)
	end

	def authorize_user!
		redirect_to posts_path, alert: "Not authorized" unless @post.user == current_user
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p><%= notice%></p>
    <p><%= alert%></p>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_with(model: @post, local: true) do |form|%>
	<div>
		<label>Title:</label>
		<%= form.text_field :title%>
	</div>

	<div>
		<label>Body:</label>
		<%= form.text_area :body%>
	</div>

	<div>
		<%= form.submit "Update Post"%>
	</div>
<%end%>

<a href="<%= post_path(@post)%>">Back to post</a>

app/views/posts/index.html.erb
<h1>All Posts</h1>
<% if user_signed_in? %>
	<div>
		<%= link_to "New Post", new_post_path, class: "btn btn-primary"%>
	</div>
<%end%>

<h2>Posts List</h2>
<% @posts.each do |post| %>
	<h3><%= link_to post.title, post%></h3>
	<p><%= link_to post.body, post%></p>
<%end%>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_with(model: @post, local: true) do |form|%>
	<div>
		<label>Title:</label>
		<%= form.text_field :title, class: "form-control"%>
	</div>

	<div>
		<label>Body:</label>
		<%= form.text_area :body, class: "form-control"%>
	</div>

	<div>
		<%= form.submit "Create Post", class: "btn btn-primary"%>
	</div>
<%end%>

<a href="<%= posts_path%>">Back to posts</a>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>

<%if user_signed_in? && @post.user == current_user%>
	<%= link_to "Edit Post", edit_post_path(@post), class: "btn btn-warning"%>
	<%= link_to "Delete Post", post_path(@post), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger"%>
<%end%>

<h3>Comments</h3>
	<% @post.comments.each do |comment|%>
		<%= comment.user.email%> : <%= comment.body%>
		<%if user_signed_in? && comment.user == current_user %>
			<%= link_to "Delete comment", post_comment_path(@post, comment), method: :delete%>
		<%end%>
	<%end%>
<ul>

<% if user_signed_in? %>
	<h3>Add a Comment</h3>
	<%= form_with(model: [@post, @post.comments.build], local: true) do |form|%>
		<div class="form-group">
			<%= form.label :body%>
			<%= form.text_area :body, class: "form-control"%>
		</div>
		<div class="form-group">
			<%= form.submit "Post comment", class: "btn btn-primary"%>
		</div>
	<%end%>
<%end%>